### PR TITLE
Update confetti-rain.js

### PR DESCRIPTION
**Pull request by mmelo**
Enable setting a custom number of confetti particles

### CODE REVIEW

**Comment by san650** [comment]
Thanks @mmelo for adding this configuration. Correct me if I'm wrong, but shouldn't we have a default value for that configuration?

The old `MAX_PARTICLES` should be the default in case people  don't set this new prop.

What do you think?

**Comment by mmelo** [comment]
Hey @san650, thank you for the quick reply, please mind this bit [here](https://github.com/mmelo/ember-confetti/blob/dd0836f750980eb0b88f9f04cc82556b543a5749/addon/components/confetti-rain.js#L78) I kept MAX_PARTICLES count as a default so it doesn't break, nor will anyone need to pass it as a config if not needed. cheers!

**Comment by san650** [comment]
@mmelo Thanks for contributing!

**Comment by san650** [comment]
@mmelo released v1.1.0 https://github.com/san650/ember-confetti/releases/tag/v1.1.0

**Comment by mmelo** [comment]
Thank you for the quick reply @san650 and for the merge 🙏

**Pull request merged**
